### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by chaspy** [chaspy/favsearch#17]
🚀

**Comment by chaspy** [comment]
📝 
ref: https://dashboard.heroku.com/apps/favsearch/deploy/heroku-git

## Login

```
 $ heroku login
heroku: Enter your login credentials
Email: take.she12@gmail.com
Password: *********
Logged in as take.she12@gmail.com
```

## Set remote

```
 $ heroku git:remote -a favsearch                                                                                                                                                        [master]
set git remote heroku to https://git.heroku.com/favsearch.git
/Users/take/go/src/github.com/chaspy/favsearch
 $ git remote -v
heroku	https://git.heroku.com/favsearch.git (fetch)
heroku	https://git.heroku.com/favsearch.git (push)
origin	git@github.com:chaspy/favsearch.git (fetch)
origin	git@github.com:chaspy/favsearch.git (push)
```

## Deploy

```
 $ git push heroku master
Counting objects: 117, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (68/68), done.
Writing objects: 100% (117/117), 18.73 KiB | 4.68 MiB/s, done.
Total 117 (delta 51), reused 107 (delta 44)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rack
remote: -----> Using Ruby version: ruby-2.4.5
remote: -----> Installing dependencies using bundler 1.15.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.6). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
remote:        Fetching gem metadata from https://rubygems.org/........
remote:        Fetching version metadata from https://rubygems.org/..
remote:        Fetching dependency metadata from https://rubygems.org/.
remote:        Fetching rake 12.3.1
remote:        Fetching public_suffix 3.0.3
remote:        Fetching backports 3.11.4
remote:        Installing rake 12.3.1
remote:        Installing public_suffix 3.0.3
remote:        Installing backports 3.11.4
remote:        Fetching buftok 0.2.0
remote:        Using bundler 1.15.2
remote:        Fetching daemons 1.2.6
remote:        Installing buftok 0.2.0
remote:        Installing daemons 1.2.6
remote:        Fetching debase-ruby_core_source 0.10.3
remote:        Fetching unf_ext 0.0.7.5
remote:        Installing unf_ext 0.0.7.5 with native extensions
remote:        Installing debase-ruby_core_source 0.10.3
remote:        Fetching equalizer 0.0.11
remote:        Installing equalizer 0.0.11
remote:        Fetching eventmachine 1.2.7
remote:        Installing eventmachine 1.2.7 with native extensions
remote:        Fetching thor 0.19.4
remote:        Installing thor 0.19.4
remote:        Fetching hashie 3.5.7
remote:        Installing hashie 3.5.7
remote:        Fetching http-form_data 2.1.1
remote:        Installing http-form_data 2.1.1
remote:        Fetching http_parser.rb 0.6.0
remote:        Installing http_parser.rb 0.6.0 with native extensions
remote:        Fetching thread_safe 0.3.6
remote:        Installing thread_safe 0.3.6
remote:        Fetching multi_json 1.13.1
remote:        Installing multi_json 1.13.1
remote:        Fetching multipart-post 2.0.0
remote:        Installing multipart-post 2.0.0
remote:        Fetching naught 1.1.0
remote:        Installing naught 1.1.0
remote:        Fetching oauth 0.5.4
remote:        Installing oauth 0.5.4
remote:        Fetching rack 1.6.10
remote:        Installing rack 1.6.10
remote:        Fetching simple_oauth 0.3.1
remote:        Installing simple_oauth 0.3.1
remote:        Fetching tilt 2.0.8
remote:        Installing tilt 2.0.8
remote:        Fetching ruby-debug-ide 0.6.1
remote:        Installing ruby-debug-ide 0.6.1 with native extensions
remote:        Fetching addressable 2.5.2
remote:        Installing addressable 2.5.2
remote:        Fetching debase 0.2.2
remote:        Installing debase 0.2.2 with native extensions
remote:        Fetching foreman 0.85.0
remote:        Installing foreman 0.85.0
remote:        Fetching unf 0.1.4
remote:        Installing unf 0.1.4
remote:        Fetching memoizable 0.4.2
remote:        Installing memoizable 0.4.2
remote:        Fetching omniauth 1.8.1
remote:        Installing omniauth 1.8.1
remote:        Fetching rack-protection 1.5.5
remote:        Installing rack-protection 1.5.5
remote:        Fetching rack-test 1.1.0
remote:        Installing rack-test 1.1.0
remote:        Fetching domain_name 0.5.20180417
remote:        Installing domain_name 0.5.20180417
remote:        Fetching omniauth-oauth 1.1.0
remote:        Installing omniauth-oauth 1.1.0
remote:        Fetching sinatra 1.4.8
remote:        Installing sinatra 1.4.8
remote:        Fetching http-cookie 1.0.3
remote:        Installing http-cookie 1.0.3
remote:        Fetching omniauth-twitter 1.4.0
remote:        Installing omniauth-twitter 1.4.0
remote:        Fetching sinatra-contrib 1.4.7
remote:        Installing sinatra-contrib 1.4.7
remote:        Fetching http 3.3.0
remote:        Installing http 3.3.0
remote:        Fetching twitter 6.2.0
remote:        Installing twitter 6.2.0
remote:        Fetching thin 1.7.2
remote:        Installing thin 1.7.2 with native extensions
remote:        Bundle complete! 9 Gemfile dependencies, 40 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (37.45s)
remote:        Cleaning up the bundler cache.
remote: -----> Detecting rake tasks
remote:
remote: ###### WARNING:
remote:
remote:        You have not declared a Ruby version in your Gemfile.
remote:        To set your Ruby version add this line to your Gemfile:
remote:        ruby '2.4.5'
remote:        # See https://devcenter.heroku.com/articles/ruby-versions for more information.
remote:
remote:
remote: -----> Discovering process types
remote:        Procfile declares types     -> web
remote:        Default types for buildpack -> console, rake
remote:
remote: -----> Compressing...
remote:        Done: 29.8M
remote: -----> Launching...
remote:        Released v4
remote:        https://favsearch.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy... done.
To https://git.heroku.com/favsearch.git
 * [new branch]      master -> master
```

but failed... 😢 

```
 $ heroku logs --tail                                                                                                                                                                    [master]
2018-10-21T05:02:29.869317+00:00 app[api]: Initial release by user take.she12@gmail.com
2018-10-21T05:02:29.948351+00:00 app[api]: Release v2 created by user take.she12@gmail.com
2018-10-21T05:02:29.869317+00:00 app[api]: Release v1 created by user take.she12@gmail.com
2018-10-21T05:02:29.948351+00:00 app[api]: Enable Logplex by user take.she12@gmail.com
2018-10-21T05:05:42.000000+00:00 app[api]: Build started by user take.she12@gmail.com
2018-10-21T05:06:27.622208+00:00 app[api]: Release v3 created by user take.she12@gmail.com
2018-10-21T05:06:27.892126+00:00 app[api]: Release v4 created by user take.she12@gmail.com
2018-10-21T05:06:27.907083+00:00 app[api]: Scaled to console@0:Free rake@0:Free web@1:Free by user take.she12@gmail.com
2018-10-21T05:06:27.622208+00:00 app[api]: Set LANG, RACK_ENV config vars by user take.she12@gmail.com
2018-10-21T05:06:27.892126+00:00 app[api]: Deploy 38ebd354 by user take.she12@gmail.com
2018-10-21T05:06:30.000000+00:00 app[api]: Build succeeded
2018-10-21T05:06:32.441032+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 4567 -s thin -o 0.0.0.0`
2018-10-21T05:07:32.770619+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-10-21T05:07:32.770735+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-10-21T05:07:32.906695+00:00 heroku[web.1]: Process exited with status 137
2018-10-21T05:07:32.925543+00:00 heroku[web.1]: State changed from starting to crashed
2018-10-21T05:07:32.927061+00:00 heroku[web.1]: State changed from crashed to starting
2018-10-21T05:07:37.964342+00:00 heroku[web.1]: Starting process with command `bundle exec rackup config.ru -p 4567 -s thin -o 0.0.0.0`
2018-10-21T05:08:38.208249+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2018-10-21T05:08:38.208249+00:00 heroku[web.1]: Stopping process with SIGKILL
2018-10-21T05:08:38.343921+00:00 heroku[web.1]: Process exited with status 137
2018-10-21T05:08:38.371787+00:00 heroku[web.1]: State changed from starting to crashed
2018-10-21T05:08:38.890121+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=favsearch.herokuapp.com request_id=4df17a77-a765-44c3-9cea-a609d3f1f5f7 fwd="180.31.204.167" dyno= connect= service= status=503 bytes= protocol=https
2018-10-21T05:08:39.659957+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=favsearch.herokuapp.com request_id=adb7b704-e387-48b0-8d9f-7529e38006aa fwd="180.31.204.167" dyno= connect= service= status=503 bytes= protocol=https
2018-10-21T05:08:40.499839+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=favsearch.herokuapp.com request_id=8995dc39-2ce9-4512-a2ea-ee5726b78632 fwd="180.31.204.167" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by chaspy** [comment]
Set environemnt varibales for key and secret.

<img width="761" alt="screenshot 2018-10-21 14 10 53" src="https://user-images.githubusercontent.com/10370988/47263368-2ed07400-d53b-11e8-948d-e3e79fc724f7.png">

**Comment by chaspy** [comment]
awesome 😄 

```
 $ heroku ps
Free dyno hours quota remaining this month: 994h 47m (99%)
Free dyno usage for this app: 0h 0m (0%)
For more information on dyno sleeping and how to upgrade, see:
https://devcenter.heroku.com/articles/dyno-sleeping

=== web (Free): bundle exec rackup config.ru -p $PORT -s thin -o 0.0.0.0 (1)
web.1: up 2018/10/21 14:34:24 +0900 (~ 7s ago)
```

Go to https://favsearch.herokuapp.com !

**Comment by chaspy** [comment]
😢 

https://favsearch.herokuapp.com/auth/twitter

```
2018-10-21T05:36:56.682081+00:00 heroku[router]: at=info method=GET path="/auth/twitter" host=favsearch.herokuapp.com request_id=24662ddb-0f2c-43a2-9f38-95110aa2fa30 fwd="180.31.204.167" dyno=web.1 connect=1ms service=112ms status=500 bytes=118 protocol=https
2018-10-21T05:36:56.679931+00:00 app[web.1]: Thin web server (v1.7.2 codename Bachmanity)
2018-10-21T05:36:56.679944+00:00 app[web.1]: Maximum connections set to 1024
2018-10-21T05:36:56.679945+00:00 app[web.1]: Listening on 0.0.0.0:54394, CTRL+C to stop
2018-10-21T05:36:56.679947+00:00 app[web.1]: I, [2018-10-21T05:35:44.726989 #4]  INFO -- omniauth: (twitter) Request phase initiated.
2018-10-21T05:36:56.679949+00:00 app[web.1]: Unexpected error while processing request: 403 Forbidden
2018-10-21T05:36:56.679951+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/oauth-0.5.4/lib/oauth/consumer.rb:236:in `token_request'
2018-10-21T05:36:56.679953+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/oauth-0.5.4/lib/oauth/consumer.rb:155:in `get_request_token'
2018-10-21T05:36:56.679955+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/omniauth-oauth-1.1.0/lib/omniauth/strategies/oauth.rb:28:in `request_phase'
2018-10-21T05:36:56.679964+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/omniauth-twitter-1.4.0/lib/omniauth/strategies/twitter.rb:61:in `request_phase'
2018-10-21T05:36:56.679967+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:224:in `request_call'
2018-10-21T05:36:56.679968+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:187:in `call!'
2018-10-21T05:36:56.679970+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/strategy.rb:168:in `call'
2018-10-21T05:36:56.679972+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.8.1/lib/omniauth/builder.rb:63:in `call'
2018-10-21T05:36:56.679973+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:225:in `context'
2018-10-21T05:36:56.679975+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:220:in `call'
2018-10-21T05:36:56.679976+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/xss_header.rb:18:in `call'
2018-10-21T05:36:56.679978+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
2018-10-21T05:36:56.679980+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
2018-10-21T05:36:56.679981+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/path_traversal.rb:16:in `call'
2018-10-21T05:36:56.679983+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/json_csrf.rb:18:in `call'
2018-10-21T05:36:56.679984+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
2018-10-21T05:36:56.679985+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/base.rb:49:in `call'
2018-10-21T05:36:56.679987+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-protection-1.5.5/lib/rack/protection/frame_options.rb:31:in `call'
2018-10-21T05:36:56.679988+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:225:in `context'
2018-10-21T05:36:56.679990+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/session/abstract/id.rb:220:in `call'
2018-10-21T05:36:56.679992+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/logger.rb:15:in `call'
2018-10-21T05:36:56.679993+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/commonlogger.rb:33:in `call'
2018-10-21T05:36:56.679995+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
2018-10-21T05:36:56.679997+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:212:in `call'
2018-10-21T05:36:56.679998+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
2018-10-21T05:36:56.680000+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/methodoverride.rb:22:in `call'
2018-10-21T05:36:56.680001+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
2018-10-21T05:36:56.680003+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
2018-10-21T05:36:56.680008+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
2018-10-21T05:36:56.680010+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
2018-10-21T05:36:56.680012+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
2018-10-21T05:36:56.680013+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
2018-10-21T05:36:56.680015+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
2018-10-21T05:36:56.680016+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
2018-10-21T05:36:56.680018+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
2018-10-21T05:36:56.680019+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
2018-10-21T05:36:56.680021+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
2018-10-21T05:36:56.680022+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
2018-10-21T05:36:56.680024+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
2018-10-21T05:36:56.680025+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
2018-10-21T05:36:56.680027+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/handler/thin.rb:19:in `run'
2018-10-21T05:36:56.680036+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/server.rb:287:in `start'
2018-10-21T05:36:56.680038+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/lib/rack/server.rb:148:in `start'
2018-10-21T05:36:56.680039+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/rack-1.6.10/bin/rackup:4:in `<top (required)>'
2018-10-21T05:36:56.680041+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/bin/rackup:23:in `load'
2018-10-21T05:36:56.680042+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/bin/rackup:23:in `<top (required)>'
2018-10-21T05:36:56.680044+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
2018-10-21T05:36:56.680046+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
2018-10-21T05:36:56.680047+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
2018-10-21T05:36:56.680049+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
2018-10-21T05:36:56.680050+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
2018-10-21T05:36:56.680052+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
2018-10-21T05:36:56.680054+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
2018-10-21T05:36:56.680055+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
2018-10-21T05:36:56.680057+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
2018-10-21T05:36:56.680058+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
2018-10-21T05:36:56.680060+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
2018-10-21T05:36:56.680061+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
2018-10-21T05:36:56.680063+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
2018-10-21T05:36:56.680064+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/bin/bundle:22:in `load'
2018-10-21T05:36:56.680066+00:00 app[web.1]: /app/vendor/bundle/ruby/2.4.0/bin/bundle:22:in `<main>'
```

@kamontia

**Comment by chaspy** [comment]
I will set custom domein.
https://devcenter.heroku.com/articles/custom-domains

**Comment by chaspy** [comment]
## Add domain

```
 $ heroku domains:add favsearch.chaspy.me
Adding favsearch.chaspy.me to ⬢ favsearch... done
 ▸    Configure your app's DNS provider to point to the DNS Target lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com.
 ▸    For help, see https://devcenter.heroku.com/articles/custom-domains

The domain favsearch.chaspy.me has been enqueued for addition
 ▸    Run heroku domains:wait 'favsearch.chaspy.me' to wait for completion
```

<img width="403" alt="screenshot 2018-10-22 01 51 31" src="https://user-images.githubusercontent.com/10370988/47269733-02e5da80-d59d-11e8-9b75-d479d8a6ba8f.png">

```
 $ host favsearch.chaspy.me                                                                                                                                                              [master]
favsearch.chaspy.me is an alias for lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com.
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 54.173.32.212
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 54.172.170.160
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 54.209.64.71
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 54.174.228.92
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 52.45.248.161
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 52.4.75.11
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 52.44.92.122
lively-dolphin-ni4ta9ya4bpub83vm50toofs.herokudns.com has address 52.45.111.123
```

Now we can access to myapp via http://favsearch.chaspy.me 🎉 
@kamontia

**Comment by chaspy** [comment]
🎉
